### ISSUE TITLE
Client authentication failed due to unknown client

### ISSUE THREAD

**Issue by laserswald** [kensanata/bitlbee-mastodon#9] opened 2018-01-09 03:23 UTC
When navigating to the URL given by the mastodon_oauth bot, my Mastodon instance refuses to give an authentication key with the message: 

> Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.

**Comment by kensanata** [comment] 2018-01-09 06:41
I’m afraid you will have to ask your instance admin about this. I didn’t know that Mastodon limited access to known clients so I assume this is a particular setting of your instance.

If they then ask you for the name of the client, I guess it would be `bitlbee-mastodon` based on `init_plugin_info` in `mastodon.c`.

**Comment by laserswald** [comment] 2018-01-13 01:22
Thanks. I'll message him.

**Comment by kensanata** [comment] 2018-01-23 13:59
@laserswald Did you resolve this?

**Comment by laserswald** [comment] 2018-01-31 02:46
No, I didn't, it slipped my mind. I just messaged him now, though.

**Comment by kensanata** [comment] 2018-02-08 11:01
As there doesn't seem to be any way for me to do anything about it so I will close this issue. If the problem is with the plugin, feel free to reopen.

**Closed by kensanata** 2018-02-08 11:01 UTC

**Comment by v0idkr4ft** [comment] 2020-05-04 23:20
I'm having this issue on the Mastodon.social instance.

**Comment by v0idkr4ft** [comment] 2020-05-05 15:19
resolved it with this https://github.com/kensanata/bitlbee-mastodon/issues/36#issuecomment-546344101 basically just had to delete account to generate new token for my instance.
